### PR TITLE
Changing code block for correctness

### PR DESCRIPTION
**Pull request by ChrisCarini**

### CODE REVIEW

**Comment by ChrisCarini** [comment]
Hi @veekaybee ! This was a great blog post, thanks for writing it up! I noticed what I believe is an incorrect code block, and have this PR for you - should take <60 seconds to review for correctness.

Happy holidays and new year!

**Comment by ChrisCarini** [comment]
@veekaybee - friendly reminder!

**Comment by ChrisCarini** [comment]
Hi @veekaybee - any chance you could take a look at this? It's a minor change, but one that prevents confusion!

**Comment by ChrisCarini** [comment]
@veekaybee - bump.

**Review by veekaybee — APPROVED** [review]

**Comment by veekaybee** [comment]
Thanks for this and for the ping!

**Comment by ChrisCarini** [comment]
No problem!

**Pull request merged**
